### ISSUE TITLE
认识 Docker

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#89]
### 运维历史

![image](https://user-images.githubusercontent.com/17792166/113465232-09aef200-9465-11eb-9308-032deb957d73.png)

* VM是一个运行在宿主机之上的完整的操作系统，VM运行自身操作系统会占用较多的CPU、内存、硬盘资源。（操作系统级别的隔离）
* Docker不同于VM，只包含应用程序以及依赖库，这使得Docker更加轻量高效，启动容器只需几秒钟之内完成。（进程级别的隔离）

[docker容器与虚拟机有什么区别？](https://www.zhihu.com/question/48174633)

### Docker 架构

![image](https://user-images.githubusercontent.com/17792166/113465228-fa2fa900-9464-11eb-8520-b70e358b0f43.png)
上图描述了 Docker 各模块之间的通信

![image](https://user-images.githubusercontent.com/17792166/113465399-38799800-9466-11eb-8504-729fcacfabb9.png)
上图描述了 Docker Engine 内部的各个重要模块

> Docker uses a client-server architecture. The Docker client talks to the Docker daemon, which does the heavy lifting of building, running, and distributing your Docker containers. The Docker client and daemon can run on the same system, or you can connect a Docker client to a remote Docker daemon. The Docker client and daemon communicate using a REST API, over UNIX sockets or a network interface. Another Docker client is Docker Compose, that lets you work with applications consisting of a set of containers.  --> [link](https://docs.docker.com/get-started/overview/)

Docker 采用 C/S 架构。Docker 客户端与 Docker 守护程序进行通信，该守护程序完成了构建，运行和分发Docker容器的繁重工作。Docker Client 可以跟 Docker 守护进程 运行在同一台机器上，也可以远程通信。Docker Client 与 Docker 守护进程 通过 RESTful API 或  CLI  命令行进行通信。 另一种 Docker 客户端是 Docker Compose，它使您可以处理由一组容器组成的应用程序。

### Docker 的几个概念

Image: 镜像，是指将应用打包好之后的存储方式，一个image包含多层layer。

Container: 基于 Image 的可运行的实例，跑起来就是一个程序进程。

Docker Registry:  镜像仓库（类比 NPM，可以拉包也可以发包），官方提供了一个公共仓库 [Docker Hub](https://hub.docker.com/search?type=image)。公司内部可以自建私有仓库。

Dockerfile: 用来描述如何构建一个镜像。

Docker-Compose: 用来定义和运行由多个容器组成的应用。

### Dockerfile 各个字段的含义

```dockerfile
# 基础镜像来源
FROM centos

# 定义镜像meta信息
LABLE maintainer="维护者"
LABLE verson="版本号"
LABEL description="描述"

# 运行命令，通过 \ 进行换行（副作用，导致 build image 的时候会分层）
RUN yum install -y vim

# 设定当前工作目录
WORKDIR /server
WORKDIR /data
RUN pwd  # 输出 /server/data

# 类似于复制黏贴
ADD . .  # 复制所有文件到 image 目录下

# 类似于复制黏贴
COPY . .  # 复制所有文件到 image 目录下

# 设置环境变量
ENV NODE_ENV production

# 数据持久化 ，也可以通过在启动 container 时指定  ---> docker run -v mysql:/var/lib/mysql
VOLUME ["/var/lib/mysql"]

# 端口暴露
EXPOSE 8080

# 设置容器启动后默认运行的命令和参数，定义多个 CMD，只有最后一个会执行
CMD echo "node env $NODE_ENV"

# 设置容器启动时运行的命令
ENTRYPOINT ['/bin/bash', './entrypoint.sh']
```

#### ADD 跟 COPY 的区别？
* ADD 能够复制并自动解压

#### CMD 、 ENTRYPOINT、 RUN 的区别？
*  CMD: 设置容器启动后默认运行的命令和参数、允许 docker run 命令跑一个 Container 时候，可以通过传参进行覆盖，使其不生效
* ENTRYPOINT：设置容器启动时运行的命令、无法通过 docker run 传参进行覆盖
* RUN：执行命令并创建新的 Image Layer

详见 [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

### Docker 的数据数据持久化

方案：
* 通过某种 mount type，将数据持久化到 Container 运行的主机硬盘或内存里
* 通过 plugin 将 Container 产品的数据缓存到第三方，比如 aws

![image](https://user-images.githubusercontent.com/17792166/113500416-6509de80-9550-11eb-943b-f7dfa4f43e5a.png)

如图，Mount Type（持久化数据的方案） 主要分几种：
* Volumes：在宿主机上会有一个特定的区域存放容器内的数据。
* Bind Mounts：将宿主机上的任意位置的目录挂在到容器。（本地开发很有用，代码改动，容器内的代码也改动，热更新能生效）
* tmpfs mounts：挂载存储在主机系统的内存中，而不会写入主机的文件系统。

#### Volumes 跟 Bind Mounts 的区别？
* Bind mount 会使得容器内对应的目录下的内容会被本机的目录覆盖掉 （本机优先）
* Bind mount 明确指定了要挂载的 本机目录 和 容器内目录 的映射关系
   * Docker Manager Volume则只指定了要对容器内的某个目录进行挂载，而挂载的是本机的哪个目录，则是由docker 本身来管理的。

详见 [Manage data in Docker](https://docs.docker.com/storage/#good-use-cases-for-tmpfs-mounts)

### Docker Compose

在本地开发一个应用时，经常需要起多个 container，比如 redis、mysql、app 等，组织和管理这些 container (启动、停止、删除、网络) 很麻烦。为了解决管理这种多容器的应用，docker-compose就诞生了。docker 也提供了 docker-compose 命令工具，```docker-compose --help```可见，通过定义```docker-compose.yml```文件，结合 docker-compose cli，就可以很简便地同时管理多个容器。

下面以我本地的 node.js 服务示例：

```yaml
version: "3.7"

services:
  db:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${HOME}/data/mysql/track:/var/lib/mysql:cached
      - ./database:/docker-entrypoint-initdb.d
    environment:   # 注入环境变量
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_USER: xxx
      MYSQL_DATABASE: xxx
      MYSQL_PASSWORD: xxx
      MYSQL_TCP_PORT: 6606
    ports:
      - 6606:6606
    networks:
      - webnet

  node:
    container_name: node_service
    working_dir: /usr/local/service
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000  # 配置端口转发，container 内部端口映射为本机端口
      - 9229:9229 # debug 暴露的端口
    environment:
      NODE_ENV: development
    volumes:
      - ./service:/usr/local/service
      - /usr/local/service/node_modules
    depends_on:
      - db
      - redis
    networks:
      - webnet
    links:
      - db
      - redis

  redis:
    image: redis:latest
    command: redis-server --requirepass xxx
    ports:
      - "6380:6379"
    volumes:
      - ${HOME}/data/redis/data:/var/lib/redis:cached
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
```

 这份 **docker-compose.yml** 文件，最主要的是 services 和 networks 这两个字段。

* services字段：定义 container，该 container 可以通过指定由本地的 dockerfile 文件构建的 Image，也可以指定远程 dockerhub 的已有 Image。其实就是如同 ```docker run``` 命令的使用，只不过把命令行换成 yaml 的各项配置。
* networks字段：定义 container 之间互调的网络，保证 container 之间网络能通。

详见 [Docker Compose](https://docs.docker.com/compose/)

### Docker 网络

* 单机网络：单机多个 Container 之间的通信
   * Bridge network（默认）
   * Host network
   * None network
* 多机网络：多台机器的 Container 之间的通信
   * Overlay network

详见 [Docker network](https://docs.docker.com/network/)

### Docker 使用到的 linux 底层技术
基于Docker的沙箱环境可以实现轻型隔离，多个容器间不会相互影响，那它使用了 linux 的哪些底层技术呢？
* Namespaces: 做隔离 pid、net、ipc、mnt、uts
* Control groups: 资源限制
* Union file systems: Container 和  Image 的分层

### Docker 常用命令

以前列举的命令可通过 ```docker COMMAND --help``` 查看详细参数与作用，比如通过```docker run --help```可以看到 docker 提供限制 Container 运行时内存跟cpu限制的参数。

#### Image 常用命令
```shell
# 查看本地已有 Image
docker image ls

# 指定 dockerfile 构建 Image
docker build -t [name:tag] -f [dockerfile_path]

# 进入指定 Image 容器环境（dockerfile 构建期间出错也可以通过 image_id 进入调试）
docker run -it [image_id] /bin/bash

# Image 发布（需要注册 docker_hub 账号）
docker push [name:tag]
```

#### Container 常用命令
```shell
# 查看本地已有 Container 
docker container ls -a \ docker ps

# 创建并运行 Container
docker run -d [image_id]

# 移除“退出”状态的 Container
docker rm $(docker container ls -f "status=exited"  -q) 

# 基于某个container创建image（不提倡，dockerfile才是主流）
docker container commit [container_id]

# 停止运行某个 Container
docker container stop [container_id]

# 打印 container 元信息
docker inspect [container_id]

# 打印 container 日志
docker logs [container_id]
```

#### Docker-Compose 常用命令
```shell
# 启动
docker compose -f dev.yml up

# 停止
docker compose -f dev.yml down
```

#### Volumes 常用命令
```shell
# 列出当前具有的 volume
docker volume ls

# 根据 volume name 查看具体的挂载信息
docker volume inspect [volume_name]  

# Container 启动时指定 
docker run -v mysql:/var/lib/mysql
```

详见 [Docker Command-line](https://docs.docker.com/engine/reference/commandline/cli/)
